title: "Khushi Sharma"
email: khushi.sharma.2201@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" 
url: "https://KhushiSharma22.github.io/" 
twitter_username: KhushiS75742437
github_username:KhushiSharma22

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
